import Head from 'next/head';

type HeadDynamicProps = {
    title: string
}

export const HeadDynamic = ({ title }: HeadDynamicProps) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}
