import type { NextPage } from 'next'
import Head from 'next/head'
import { useQuery } from 'react-query';

import Header from '../components/Header';
import { ContentCloud } from '../components/ContentCloud';

const Home: NextPage = () => {
  async function fetchData() {
    const res = await fetch('https://swapi.dev/api/people/?format=json');
    const data = await res.json();
    return data.results;
  }

  const { data } = useQuery('characters', fetchData)

  return (
    <div>
      <Head>
        <title>Luke & Friends</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <ContentCloud characters={data} />
      </main>
    </div>
  )
}

export default Home
